USE GD2C2022
GO



-- BORRADO DE PROCEDURES/

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_MARCA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_MARCA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_MARCA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CATEGORIA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CATEGORIA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CATEGORIA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_MATERIAL') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_MATERIAL
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_MATERIAL eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_TIPO_VARIANTE') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_TIPO_VARIANTE
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_TIPO_VARIANTE eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_VARIANTE') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_VARIANTE
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_VARIANTE eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PRODUCTO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PRODUCTO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PRODUCTO eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PRODUCTO_VARIANTE') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PRODUCTO_VARIANTE
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PRODUCTO_VARIANTE eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_VENTA_POR_PRODUCTO') IS NOT NULL
BEGIN
	DROP
	 PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA_POR_PRODUCTO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_VENTA_POR_PRODUCTO eliminado')
END
----
IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CUPON_TIPO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON_TIPO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CUPON_TIPO eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CUPON') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CUPON eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CANAL') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CANAL
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CANAL eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PROVINCIA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVINCIA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PROVINCIA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_LOCALIDAD') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_LOCALIDAD
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_LOCALIDAD eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_COMPRA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_COMPRA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_COMPRA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PROVEEDOR') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVEEDOR
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PROVEEDOR eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CLIENTE') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CLIENTE
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CLIENTE eliminado')
END



-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/


/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA MEDIO_ENVIO_POR_LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO
END
GO


/*BORRO CONSTRAINS FK A LA TABLA COMPRA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_MEDIO_DE_PAGO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_MEDIO_DE_PAGO_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_PROVEEDOR
END
GO

/*BORRO CONSTRAINS FK A LA TABLA DESCUENTO_COMPRA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA PROVEEDOR*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR DROP CONSTRAINT FK_PROVEEDOR_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA COMPRA_POR_PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO
/*BORRO CONSTRAINS FK A LA TABLA CLIENTE*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE DROP CONSTRAINT FK_CLIENTE_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON DROP CONSTRAINT FK_CUPON_CUPON_TIPO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON DROP CONSTRAINT FK_VENTA_POR_CUPON_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA DESCUENTO_POR_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MARCA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MATERIAL
END
GO
/*BORRO CONSTRAINS FK A LA TABLA VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_CANAL
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_VENTA_POR_CUPON
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_MEDIO_DE_PAGO_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_CLIENTE
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD
END
GO


/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_CATEGORIA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MATERIAL
END
GO


/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO_VARIANTE*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_VARIANTE_PRODUCTO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_VARIANTE_VARIANTE
END
GO


/*BORRO CONSTRAINS FK A LA TABLA VARIANTE*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VARIANTE_TIPO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VARIANTE DROP CONSTRAINT FK_VARIANTE_TIPO_VARIANTE
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_POR_PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO DROP CONSTRAINT FK_VENTA_POR_PRODUCTO_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO DROP CONSTRAINT FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_POR_CUPON*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON DROP CONSTRAINT FK_VENTA_POR_CUPON_CUPON
END
GO
























-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('HARAKIRI.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.LOCALIDAD
	PRINT('Tabla HARAKIRI.LOCALIDAD eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVINCIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVINCIA
	PRINT('Tabla HARAKIRI.PROVINCIA eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVEEDOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVEEDOR
	PRINT('Tabla HARAKIRI.PROVEEDOR eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA
	PRINT('Tabla HARAKIRI.COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.CLIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CLIENTE
	PRINT('Tabla HARAKIRI.CLIENTE eliminada')
END

IF OBJECT_ID('HARAKIRI.MATERIAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MATERIAL
	PRINT('Tabla HARAKIRI.MATERIAL eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON_TIPO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON_TIPO
	PRINT('Tabla HARAKIRI.CUPON_TIPO eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON
	PRINT('Tabla HARAKIRI.CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.CANAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CANAL
	PRINT('Tabla HARAKIRI.CANAL eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA_POR_CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA_POR_CUPON
	PRINT('Tabla HARAKIRI.VENTA_POR_CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_CONCEPTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_CONCEPTO
	PRINT('Tabla HARAKIRI.DESCUENTO_CONCEPTO eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_POR_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_POR_VENTA
	PRINT('Tabla HARAKIRI.DESCUENTO_POR_VENTA eliminada')
END
IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_VENTA eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO eliminada')
END

IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_COMPRA
	PRINT('Tabla HARAKIRI.DESCUENTO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA_POR_PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	PRINT('Tabla HARAKIRI.COMPRA_POR_PRODUCTO eliminada')
END


IF OBJECT_ID('HARAKIRI.PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PRODUCTO
	PRINT('Tabla HARAKIRI.PRODUCTO eliminada')
END

IF OBJECT_ID('HARAKIRI.PRODUCTO_VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PRODUCTO_VARIANTE
	PRINT('Tabla HARAKIRI.PRODUCTO_VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VARIANTE
	PRINT('Tabla HARAKIRI.VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.CATEGORIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CATEGORIA
	PRINT('Tabla HARAKIRI.CATEGORIA eliminada')
END

IF OBJECT_ID('HARAKIRI.MARCA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MARCA
	PRINT('Tabla HARAKIRI.MARCA eliminada')
END

IF OBJECT_ID('HARAKIRI.TIPO_VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.TIPO_VARIANTE
	PRINT('Tabla HARAKIRI.TIPO_VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA_POR_PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA_POR_PRODUCTO
	PRINT('Tabla HARAKIRI.VENTA_POR_PRODUCTO eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA
	PRINT('Tabla HARAKIRI.VENTA eliminada')
END

/*BORRADO DE PROCEDURES*/

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_LOCALIDAD') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_LOCALIDAD
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_LOCALIDAD eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PROVINCIA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVINCIA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PROVINCIA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_COMPRA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_COMPRA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_COMPRA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_PROVEEDOR') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVEEDOR
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_PROVEEDOR eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CLIENTE') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CLIENTE
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CLIENTE eliminado')
END



IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CUPON_TIPO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON_TIPO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CUPON_TIPO eliminado')
END

IF OBJECT_ID('HARAKIRI.HARAKIRI.MIGRAR_TABLA_CUPON') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CUPON eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_CANAL') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_CANAL
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_CANAL eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA eliminado')
END

IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_VENTA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_VENTA eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_MEDIO_ENVIO') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_ENVIO
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_MEDIO_ENVIO eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA eliminado')
END


IF OBJECT_ID('HARAKIRI.MIGRAR_TABLA_DESCUENTO_COMPRA') IS NOT NULL
BEGIN
	DROP PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_COMPRA
	PRINT('Procedure HARAKIRI.MIGRAR_TABLA_DESCUENTO_COMPRA eliminado')
END

-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'HARAKIRI')
BEGIN
   DROP SCHEMA HARAKIRI
   PRINT('Esquema HARAKIRI borrado')
END
GO

USE GD2C2022
GOUSE GD2C2022
GO
----------------------------------------------------------------------------------------------------------
/*CREACION DE ESQUEMA*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'HARAKIRI')
BEGIN
    EXEC ('CREATE SCHEMA HARAKIRI')
	PRINT('Esquema HARAKIRI creado')
END
GOUSE GD2C2022
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PROVEEDOR') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PROVEEDOR (
		
        PROVEEDOR_CUIT nvarchar(50) NOT NULL,
        PROVEEDOR_LOCALIDAD_CODIGO decimal(18,0) NOT NULL, --FK A LOCALIDAD
        PROVEEDOR_RAZON_SOCIAL nvarchar(50) NOT NULL, 
        PROVEEDOR_DOMICILIO nvarchar(50) NOT NULL, 
        PROVEEDOR_MAIL nvarchar(50) NOT NULL
	)
	PRINT('Tabla HARAKIRI.PROVEEDOR creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.LOCALIDAD (
		
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_PROVINCIA_CODIGO decimal(18,0) NOT NULL,
        LOCALIDAD_NOMBRE NVARCHAR(255) NOT NULL,
        LOCALIDAD_CODIGO_POSTAL decimal(18,0) NOT NULL
	)
	PRINT('Tabla HARAKIRI.LOCALIDAD creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PROVINCIA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PROVINCIA (
		
        PROVINCIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        PROVINCIA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.PROVINCIA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.COMPRA (
		
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        COMPRA_MEDIO_DE_PAGO_CODIGO decimal(19,0), --FK
        PROVEEDOR_CUIT nvarchar(50), --FK
        COMPRA_FECHA date,
        COMPRA_TOTAL decimal(18,2)
	)
	PRINT('Tabla HARAKIRI.COMPRA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA (
		
        VENTA_CODIGO decimal(19,0) NOT NULL,
        VENTA_CANAL_CODIGO decimal(19,0),
        VENTA_CUPON_CODIGO nvarchar(255),
        VENTA_MEDIO_DE_PAGO_CODIGO decimal(19, 0),
        VENTA_CLIENTE_CODIGO decimal(19, 0),
        VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19, 0),
        VENTA_FECHA date,
        VENTA_TOTAL decimal(18, 2)
	)
	PRINT('Tabla HARAKIRI.VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_DE_PAGO_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA (

        MEDIO_DE_PAGO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_DE_PAGO_NOMBRE NVARCHAR(255) NOT NULL,
        MEDIO_DE_PAGO_COSTO decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_ENVIO_POR_LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD (

        MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL,
        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL,
        VENTA_ENVIO_PRECIO decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_ENVIO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_ENVIO (

        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_ENVIO_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CLIENTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CLIENTE (

	CLIENTE_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CLIENTE_NOMBRE nvarchar(255) NOT NULL,
        CLIENTE_APELLIDO nvarchar(255) NOT NULL ,
        CLIENTE_DNI decimal(18,0) NOT NULL,
        CLIENTE_DIRECCION nvarchar(255) NOT NULL,
        CLIENTE_TELEFONO decimal(18,0) NOT NULL,
        CLIENTE_MAIL nvarchar(255) NOT NULL,
        CLIENTE_FECHA_NAC date NOT NULL,
        CLIENTE_LOCALIDAD_CODIGO decimal(18,0) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CLIENTE creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MATERIAL') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MATERIAL (
                
	MATERIAL_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MATERIAL_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.MATERIAL creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CUPON_TIPO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CUPON_TIPO (

        CUPON_TIPO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CUPON_TIPO_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CUPON_TIPO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CUPON') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CUPON (

        CUPON_CODIGO nvarchar(255) NOT NULL,
        CUPON_TIPO_CODIGO decimal(19,0),
        CUPON_FECHA_DESDE date,
        CUPON_FECHA_HASTA date,
        CUPON_VALOR decimal(18,2)
        )
	PRINT('Tabla HARAKIRI.CUPON creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CANAL') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CANAL (

        CANAL_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CANAL_NOMBRE nvarchar(2555),
        CANAL_COSTO decimal(18,2)
        )
	PRINT('Tabla HARAKIRI.CANAL creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA_POR_CUPON') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA_POR_CUPON (

        VENTA_POR_CUPON_CODIGO decimal (19,0) NOT NULL IDENTITY(1,1),       
        CUPON_CODIGO nvarchar(255) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        CUPON_IMPORTE decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.VENTA_POR_CUPON creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_CONCEPTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_CONCEPTO (
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_NOMBRE nvarchar(255) NOT NULL
        )
	PRINT('Tabla HARAKIRI.DESCUENTO_CONCEPTO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_POR_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_POR_VENTA (
        DESCUENTO_POR_VENTA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        DESCUENTO_IMPORTE decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.DESCUENTO_POR_VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_DE_PAGO_COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA (

        MEDIO_DE_PAGO_COMPRA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_COMPRA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_COMPRA (

        DESCUENTO_COMPRA_CODIGO decimal(19,0) NOT NULL,
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        DESCUENTO_COMPRA_VALOR decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.DESCUENTO_COMPRA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].COMPRA_POR_PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.COMPRA_POR_PRODUCTO (
        COMPRA_POR_PRODUCTO_CODIGO decimal (19,0) NOT NULL IDENTITY(1,1),
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        PRODUCTO_VARIANTE_CODIGO NVARCHAR(50) NOT NULL,
        PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
        PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.COMPRA_POR_PRODUCTO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CATEGORIA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CATEGORIA (
                
	CATEGORIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        CATEGORIA_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CATEGORIA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MARCA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MARCA (
                
	MARCA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MARCA_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.MARCA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PRODUCTO (
	PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_MARCA_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_MATERIAL_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_CATEGORIA_CODIGO decimal(18,0) NOT NULL ,
        PRODUCTO_NOMBRE nvarchar(50)  NOT NULL ,
        PRODUCTO_DESCRIPCION nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.PRODUCTO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PRODUCTO_VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PRODUCTO_VARIANTE (
	PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        VARIANTE_CODIGO decimal (18,0) NOT NULL,
        PRECIO_ACTUAL_COMPRA decimal(18,2) NOT NULL,
        PRECIO_ACTUAL_VENTA decimal(18,2)  
        )
	PRINT('Tabla HARAKIRI.PRODUCTO_VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VARIANTE (
	VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1) ,
        VARIANTE_TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL,
        VARIANTE_NOMBRE nvarchar (50) NOT NULL,
     
        )
	PRINT('Tabla HARAKIRI.VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].TIPO_VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.TIPO_VARIANTE (
	TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1) ,
        TIPO_VARIANTE_VALOR nvarchar (50) NOT NULL,
     
        )
	PRINT('Tabla HARAKIRI.TIPO_VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA_POR_PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA_POR_PRODUCTO (
                
        PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
        PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.VENTA_POR_PRODUCTO creada')
END
GO
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT FK PARA LAS TABLAS DE LA BASE DE DATOS */

/*AGREGANDO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD
	ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY(LOCALIDAD_PROVINCIA_CODIGO) REFERENCES HARAKIRI.PROVINCIA(PROVINCIA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.LOCALIDAD y HARAKIRI.PROVINCIA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA MEDIO_ENVIO_POR_LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD y HARAKIRI.LOCALIDAD agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO FOREIGN KEY(MEDIO_ENVIO_CODIGO) REFERENCES HARAKIRI.MEDIO_ENVIO(MEDIO_ENVIO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD y HARAKIRI.MEDIO_ENVIO agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT FK_COMPRA_MEDIO_DE_PAGO FOREIGN KEY(COMPRA_MEDIO_DE_PAGO_CODIGO) REFERENCES HARAKIRI.MEDIO_DE_PAGO_COMPRA(MEDIO_DE_PAGO_COMPRA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA y HARAKIRI.MEDIO_DE_PAGO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY(PROVEEDOR_CUIT) REFERENCES HARAKIRI.PROVEEDOR(PROVEEDOR_CUIT)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA y HARAKIRI.PROVEEDOR agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON
	ADD CONSTRAINT FK_CUPON_CUPON_TIPO FOREIGN KEY(CUPON_TIPO_CODIGO) REFERENCES HARAKIRI.CUPON_TIPO(CUPON_TIPO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.CUPON y HARAKIRI.CUPON_TIPO agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA_POR_CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_CUPON FOREIGN KEY(CUPON_CODIGO) REFERENCES HARAKIRI.CUPON(CUPON_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_CUPON y HARAKIRI.CUPON agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_CUPON y HARAKIRI.VENTA agregada')
END
GO


/*AGREGANDO CONSTRAINS FK A LA TABLA DESCUENTO_POR_VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO FOREIGN KEY(DESCUENTO_CONCEPTO_CODIGO) REFERENCES HARAKIRI.DESCUENTO_CONCEPTO(DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_POR_VENTA y HARAKIRI.DESCUENTO_CONCEPTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_POR_VENTA y HARAKIRI.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA DESCUENTO_COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA
	ADD CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES HARAKIRI.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_COMPRA y HARAKIRI.COMPRA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA COMPRA_POR_PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES HARAKIRI.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA_POR_PRODUCTO y HARAKIRI.COMPRA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES HARAKIRI.PRODUCTO_VARIANTE (PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA_POR_PRODUCTO y HARAKIRI.PRODUCTO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PROVEEDOR*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR
	ADD CONSTRAINT FK_PROVEEDOR_LOCALIDAD FOREIGN KEY(PROVEEDOR_LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.LOCALIDAD y HARAKIRI.PROVEEDOR agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA CLIENTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE
	ADD CONSTRAINT FK_CLIENTE_LOCALIDAD FOREIGN KEY(CLIENTE_LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.CLIENTE y HARAKIRI.LOCALIDAD agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY(PRODUCTO_MARCA_CODIGO) REFERENCES HARAKIRI.MARCA(MARCA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.MARCA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY(PRODUCTO_CATEGORIA_CODIGO) REFERENCES HARAKIRI.CATEGORIA(CATEGORIA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.CATEGORIA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MATERIAL FOREIGN KEY(PRODUCTO_MATERIAL_CODIGO) REFERENCES HARAKIRI.MATERIAL(MATERIAL_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.MATERIAL agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PRODUCTO_VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_PRODUCTO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES HARAKIRI.PRODUCTO(PRODUCTO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO_VARIANTE y HARAKIRI.PRODUCTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_VARIANTE FOREIGN KEY(VARIANTE_CODIGO) REFERENCES HARAKIRI.VARIANTE(VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO_VARIANTE y HARAKIRI.VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VARIANTE_TIPO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VARIANTE
	ADD CONSTRAINT FK_VARIANTE_TIPO_VARIANTE FOREIGN KEY(VARIANTE_TIPO_VARIANTE_CODIGO) REFERENCES HARAKIRI.TIPO_VARIANTE(TIPO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VARIANTE y HARAKIRI.TIPO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA_POR_PRODUCTO*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES HARAKIRI.PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_PRODUCTO y HARAKIRI.PRODUCTO_VARIANTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_PRODUCTO y HARAKIRI.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_CANAL FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES HARAKIRI.CANAL(CANAL_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CANAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_VENTA_POR_CUPON FOREIGN KEY(VENTA_CUPON_CODIGO) REFERENCES HARAKIRI.CUPON(CUPON_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CUPON agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_DE_PAGO_VENTA FOREIGN KEY(VENTA_MEDIO_DE_PAGO_CODIGO) REFERENCES HARAKIRI.MEDIO_DE_PAGO_VENTA(MEDIO_DE_PAGO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.MEDIO_DE_PAGO_VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY(VENTA_CLIENTE_CODIGO) REFERENCES HARAKIRI.CLIENTE(CLIENTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CLIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD(MEDIO_ENVIO_POR_LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.LOCALIDAD agregada')
END
GO-- Acá van los create de los procedures y los EXEC de ellos
USE GD2C2022
GO
---------------------------------------------------------------------------------------



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_VARIANTE
AS
BEGIN
INSERT INTO HARAKIRI.VARIANTE (VARIANTE_TIPO_VARIANTE_CODIGO,VARIANTE_NOMBRE )
SELECT DISTINCT T.TIPO_VARIANTE_CODIGO,PRODUCTO_VARIANTE
FROM  gd_esquema.Maestra M JOIN HARAKIRI.TIPO_VARIANTE T ON M.PRODUCTO_TIPO_VARIANTE = T.TIPO_VARIANTE_VALOR WHERE PRODUCTO_VARIANTE IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.VARIANTE)
PRINT('Datos migrados a la tabla HARAKIRI.VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_TIPO_VARIANTE
AS
BEGIN
INSERT INTO HARAKIRI.TIPO_VARIANTE (TIPO_VARIANTE_VALOR)
SELECT DISTINCT PRODUCTO_TIPO_VARIANTE AS TIPO_VARIANTE_VALOR
FROM gd_esquema.Maestra WHERE PRODUCTO_TIPO_VARIANTE IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.TIPO_VARIANTE)
PRINT('Datos migrados a la tabla HARAKIRI.TIPO_VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_MARCA
AS
BEGIN
INSERT INTO HARAKIRI.MARCA (MARCA_NOMBRE)
SELECT DISTINCT PRODUCTO_MARCA AS MARCA_NOMBRE
FROM gd_esquema.Maestra WHERE PRODUCTO_MARCA IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MARCA)
PRINT('Datos migrados a la tabla HARAKIRI.MARCA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVINCIA
AS
BEGIN 
  INSERT INTO HARAKIRI.PROVINCIA (PROVINCIA_NOMBRE)
  SELECT DISTINCT CLIENTE_PROVINCIA
  FROM GD_ESQUEMA.MAESTRA
  WHERE CLIENTE_PROVINCIA IS NOT NULL
  UNION
  SELECT DISTINCT PROVEEDOR_PROVINCIA
  FROM GD_ESQUEMA.MAESTRA
  WHERE PROVEEDOR_PROVINCIA IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PROVINCIA)
PRINT('Datos migrados a la tabla HARAKIRI.PROVINCIA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_LOCALIDAD
AS
BEGIN 
INSERT INTO HARAKIRI.LOCALIDAD (LOCALIDAD_PROVINCIA_CODIGO, LOCALIDAD_NOMBRE, LOCALIDAD_CODIGO_POSTAL)

  SELECT DISTINCT P.PROVINCIA_CODIGO, MA.CLIENTE_LOCALIDAD, MA.CLIENTE_CODIGO_POSTAL
  FROM gd_esquema.Maestra MA JOIN HARAKIRI.PROVINCIA P ON MA.CLIENTE_PROVINCIA = P.PROVINCIA_NOMBRE
  UNION
  SELECT DISTINCT P.PROVINCIA_CODIGO, MA.PROVEEDOR_LOCALIDAD, MA.PROVEEDOR_CODIGO_POSTAL
  FROM gd_esquema.Maestra MA JOIN HARAKIRI.PROVINCIA P ON MA.PROVEEDOR_PROVINCIA = P.PROVINCIA_NOMBRE

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.LOCALIDAD)
PRINT('Datos migrados a la tabla HARAKIRI.LOCALIDAD. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_CLIENTE
AS
BEGIN 
  INSERT INTO HARAKIRI.CLIENTE (CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, CLIENTE_LOCALIDAD_CODIGO)
  SELECT DISTINCT CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, L.LOCALIDAD_CODIGO
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.LOCALIDAD L ON MA.CLIENTE_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.CLIENTE_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
  WHERE CLIENTE_NOMBRE IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MATERIAL)
PRINT('Datos migrados a la tabla HARAKIRI.MATERIAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_PROVEEDOR
AS
BEGIN 
  INSERT INTO HARAKIRI.PROVEEDOR (PROVEEDOR_CUIT, PROVEEDOR_LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL)
  SELECT DISTINCT PROVEEDOR_CUIT, L.LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.LOCALIDAD L ON MA.PROVEEDOR_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.PROVEEDOR_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
  WHERE PROVEEDOR_CUIT IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PROVEEDOR)
PRINT('Datos migrados a la tabla HARAKIRI.PROVEEDOR. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_COMPRA
AS
BEGIN 
  INSERT INTO HARAKIRI.COMPRA (COMPRA_NUMERO, COMPRA_MEDIO_DE_PAGO_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL)
  SELECT DISTINCT COMPRA_NUMERO, MPC.MEDIO_DE_PAGO_COMPRA_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.MEDIO_DE_PAGO_COMPRA MPC ON MA.COMPRA_MEDIO_PAGO = MPC.MEDIO_DE_PAGO_COMPRA_NOMBRE
  WHERE COMPRA_NUMERO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.COMPRA)
PRINT('Datos migrados a la tabla HARAKIRI.COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_CATEGORIA
AS
BEGIN
INSERT INTO HARAKIRI.CATEGORIA (CATEGORIA_NOMBRE)
SELECT DISTINCT PRODUCTO_CATEGORIA AS CATEGORIA_NOMBRE
FROM gd_esquema.Maestra WHERE PRODUCTO_CATEGORIA IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.CATEGORIA)
PRINT('Datos migrados a la tabla HARAKIRI.MARCA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON_TIPO
AS
BEGIN
INSERT INTO HARAKIRI.CUPON_TIPO (CUPON_TIPO_NOMBRE)
SELECT DISTINCT M.VENTA_CUPON_TIPO
FROM gd_esquema.Maestra M WHERE M.VENTA_CUPON_TIPO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.CUPON_TIPO)
PRINT('Datos migrados a la tabla HARAKIRI.CUPON_TIPO. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_MATERIAL
AS
BEGIN
INSERT INTO HARAKIRI.MATERIAL (MATERIAL_NOMBRE)
SELECT DISTINCT PRODUCTO_MATERIAL AS MATERIAL_NOMBRE
FROM gd_esquema.Maestra WHERE PRODUCTO_MATERIAL IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MATERIAL)
PRINT('Datos migrados a la tabla HARAKIRI.MATERIAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_CUPON
AS
BEGIN
INSERT INTO HARAKIRI.CUPON (CUPON_CODIGO, CUPON_TIPO_CODIGO, CUPON_FECHA_DESDE, CUPON_FECHA_HASTA, CUPON_VALOR)
SELECT DISTINCT 
    M.VENTA_CUPON_CODIGO CUPON_CODIGO,
	CT.CUPON_TIPO_CODIGO CUPON_TIPO_CODIGO,
	M.VENTA_CUPON_FECHA_DESDE CUPON_FECHA_DESDE,
	M.VENTA_CUPON_FECHA_HASTA CUPON_FECHA_HASTA,
	M.VENTA_CUPON_VALOR CUPON_VALOR
FROM gd_esquema.Maestra M
JOIN HARAKIRI.CUPON_TIPO CT on CT.CUPON_TIPO_NOMBRE = M.VENTA_CUPON_TIPO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.CUPON)
PRINT('Datos migrados a la tabla HARAKIRI.CUPON. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_PRODUCTO
AS
BEGIN
INSERT INTO HARAKIRI.PRODUCTO
SELECT DISTINCT MA.PRODUCTO_CODIGO AS PRODUCTO_CODIGO,
 M.MARCA_CODIGO AS PRODUCTO_MARCA_CODIGO,MT.MATERIAL_CODIGO AS  PRODUCTO_MATERIAL_CODIGO ,
  CA.CATEGORIA_CODIGO AS  PRODUCTO_CATEGORIA_CODIGO ,
 MA.PRODUCTO_NOMBRE AS PRODUCTO_NOMBRE, MA.PRODUCTO_DESCRIPCION AS  PRODUCTO_DESCRIPCION
FROM gd_esquema.Maestra MA JOIN HARAKIRI.MARCA M ON MA.PRODUCTO_MARCA = M.MARCA_NOMBRE 
JOIN HARAKIRI.MATERIAL MT ON MA.PRODUCTO_MATERIAL = MT.MATERIAL_NOMBRE 
JOIN HARAKIRI.CATEGORIA CA ON MA.PRODUCTO_CATEGORIA = CA.CATEGORIA_NOMBRE 
WHERE PRODUCTO_CODIGO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PRODUCTO)
PRINT('Datos migrados a la tabla HARAKIRI.PRODUCTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON
AS
BEGIN
INSERT INTO HARAKIRI.VENTA_POR_CUPON (CUPON_CODIGO, VENTA_CODIGO, CUPON_IMPORTE)
SELECT DISTINCT 
	M.VENTA_CUPON_CODIGO,
	M.VENTA_CODIGO,
	M.VENTA_CUPON_IMPORTE
FROM gd_esquema.Maestra M
WHERE M.VENTA_CUPON_CODIGO IS NOT NULL AND M.VENTA_CODIGO IS NOT NULL AND M.VENTA_CUPON_IMPORTE IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.VENTA_POR_CUPON)
PRINT('Datos migrados a la tabla HARAKIRI.VENTA_POR_CUPON. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_PRODUCTO_VARIANTE
AS
BEGIN
INSERT INTO HARAKIRI.PRODUCTO_VARIANTE
SELECT DISTINCT MA.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO_VARIANTE_CODIGO,
 P.PRODUCTO_CODIGO AS PRODUCTO_CODIGO,V.VARIANTE_CODIGO AS  VARIANTE_CODIGO ,
 max(COMPRA_PRODUCTO_PRECIO) AS PRECIO_ACTUAL_COMPRA
,max(VENTA_PRODUCTO_PRECIO) AS PRECIO_ACTUAL_VENTA
FROM gd_esquema.Maestra MA JOIN HARAKIRI.PRODUCTO P ON MA.PRODUCTO_CODIGO = P.PRODUCTO_CODIGO 
JOIN HARAKIRI.VARIANTE V ON V.VARIANTE_NOMBRE = MA.PRODUCTO_VARIANTE 
WHERE PRODUCTO_VARIANTE_CODIGO IS NOT NULL
group by PRODUCTO_VARIANTE_CODIGO ,P.PRODUCTO_CODIGO,V.VARIANTE_CODIGO
order by PRODUCTO_VARIANTE_CODIGO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PRODUCTO_VARIANTE)
PRINT('Datos migrados a la tabla HARAKIRI.PRODUCTO_VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_CANAL
AS
BEGIN
INSERT INTO HARAKIRI.CANAL (CANAL_NOMBRE, CANAL_COSTO)
SELECT DISTINCT 
	M.VENTA_CANAL,
	M.VENTA_CANAL_COSTO
FROM gd_esquema.Maestra M
WHERE M.VENTA_CANAL IS NOT NULL AND M.VENTA_CANAL_COSTO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.CANAL)
PRINT('Datos migrados a la tabla HARAKIRI.CANAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA_POR_PRODUCTO
AS
BEGIN
INSERT INTO HARAKIRI.VENTA_POR_PRODUCTO
SELECT  V.VENTA_CODIGO AS VENTA_CODIGO,
 P.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO_VARIANTE_CODIGO,
 MA.VENTA_PRODUCTO_CANTIDAD AS PRODUCTO_CANTIDAD
,MA.VENTA_PRODUCTO_CANTIDAD*MA.VENTA_PRODUCTO_PRECIO AS PRODUCTO_PRECIO_TOTAL
FROM gd_esquema.Maestra MA JOIN HARAKIRI.VENTA V ON MA.VENTA_CODIGO = V.VENTA_CODIGO 
JOIN HARAKIRI.PRODUCTO_VARIANTE P ON P.PRODUCTO_VARIANTE_CODIGO = MA.PRODUCTO_VARIANTE_CODIGO 
order by VENTA_CODIGO,PRODUCTO_VARIANTE_CODIGO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.VENTA_POR_PRODUCTO)
PRINT('Datos migrados a la tabla HARAKIRI.VENTA_POR_PRODUCTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA
AS
BEGIN
INSERT INTO HARAKIRI.DESCUENTO_POR_VENTA (DESCUENTO_CONCEPTO_CODIGO, VENTA_CODIGO, DESCUENTO_IMPORTE)
SELECT DISTINCT 
	DC.DESCUENTO_CONCEPTO_CODIGO,
	M.VENTA_CODIGO,
	M.VENTA_DESCUENTO_IMPORTE
FROM gd_esquema.Maestra M
JOIN HARAKIRI.DESCUENTO_CONCEPTO DC on DC.DESCUENTO_CONCEPTO_NOMBRE= M.VENTA_DESCUENTO_CONCEPTO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.DESCUENTO_POR_VENTA)
PRINT('Datos migrados a la tabla HARAKIRI.DESCUENTO_POR_VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO
AS
BEGIN
INSERT INTO HARAKIRI.DESCUENTO_CONCEPTO (DESCUENTO_CONCEPTO_NOMBRE)
SELECT DISTINCT 
	M.VENTA_DESCUENTO_CONCEPTO
FROM gd_esquema.Maestra M
WHERE M.VENTA_DESCUENTO_CONCEPTO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.DESCUENTO_CONCEPTO)
PRINT('Datos migrados a la tabla HARAKIRI.DESCUENTO_CONCEPTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA
AS
BEGIN 
  INSERT INTO HARAKIRI.MEDIO_DE_PAGO_VENTA (MEDIO_DE_PAGO_NOMBRE, MEDIO_DE_PAGO_COSTO)
  SELECT DISTINCT VENTA_MEDIO_PAGO, VENTA_MEDIO_PAGO_COSTO
  FROM GD_ESQUEMA.MAESTRA
  WHERE VENTA_MEDIO_PAGO IS NOT NULL AND VENTA_MEDIO_PAGO_COSTO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MEDIO_DE_PAGO_VENTA)
PRINT('Datos migrados a la tabla HARAKIRI.MEDIO_DE_PAGO_VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_VENTA
AS
BEGIN 
  INSERT INTO HARAKIRI.VENTA (MEDIO_DE_PAGO_NOMBRE, MEDIO_DE_PAGO_COSTO)
  SELECT DISTINCT VENTA_MEDIO_PAGO, VENTA_MEDIO_PAGO_COSTO
  FROM GD_ESQUEMA.MAESTRA
  WHERE VENTA_MEDIO_PAGO IS NOT NULL AND VENTA_MEDIO_PAGO_COSTO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MEDIO_DE_PAGO_VENTA)
PRINT('Datos migrados a la tabla HARAKIRI.VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_ENVIO
AS
BEGIN 
  INSERT INTO HARAKIRI.MEDIO_ENVIO (MEDIO_ENVIO_NOMBRE)
  SELECT DISTINCT 
	M.VENTA_MEDIO_ENVIO MEDIO_ENVIO_NOMBRE
  FROM gd_esquema.Maestra M
  WHERE M.VENTA_MEDIO_ENVIO IS NOT NULL 

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MEDIO_ENVIO)
PRINT('Datos migrados a la tabla HARAKIRI.MEDIO_ENVIO. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA
AS
BEGIN 
  INSERT INTO HARAKIRI.MEDIO_DE_PAGO_COMPRA (MEDIO_DE_PAGO_COMPRA_NOMBRE)
  SELECT DISTINCT 
	M.COMPRA_MEDIO_PAGO MEDIO_DE_PAGO_COMPRA_NOMBRE
  FROM gd_esquema.Maestra M
  WHERE M.COMPRA_MEDIO_PAGO IS NOT NULL 

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MEDIO_DE_PAGO_COMPRA)
PRINT('Datos migrados a la tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO



CREATE PROCEDURE HARAKIRI.MIGRAR_TABLA_DESCUENTO_COMPRA
AS
BEGIN 
  INSERT INTO HARAKIRI.DESCUENTO_COMPRA (DESCUENTO_COMPRA_CODIGO,COMPRA_NUMERO,DESCUENTO_COMPRA_VALOR)
  SELECT DISTINCT 
    M.DESCUENTO_COMPRA_CODIGO,
    M.COMPRA_NUMERO,
	M.DESCUENTO_COMPRA_VALOR 
  FROM gd_esquema.Maestra M
  WHERE DESCUENTO_COMPRA_CODIGO IS NOT NULL AND COMPRA_NUMERO IS NOT NULL AND DESCUENTO_COMPRA_VALOR IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.DESCUENTO_COMPRA)
PRINT('Datos migrados a la tabla HARAKIRI.DESCUENTO_COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)

END
GO

EXEC HARAKIRI.MIGRAR_TABLA_CUPON_TIPO
EXEC HARAKIRI.MIGRAR_TABLA_CUPON
/*EXEC HARAKIRI.MIGRAR_TABLA_VENTA_POR_CUPON*/
EXEC HARAKIRI.MIGRAR_TABLA_CANAL
/*EXEC HARAKIRI.MIGRAR_TABLA_DESCUENTO_POR_VENTA*/
EXEC HARAKIRI.MIGRAR_TABLA_DESCUENTO_CONCEPTO

EXEC HARAKIRI.MIGRAR_TABLA_PROVINCIA
EXEC HARAKIRI.MIGRAR_TABLA_LOCALIDAD
EXEC HARAKIRI.MIGRAR_TABLA_COMPRA
EXEC HARAKIRI.MIGRAR_TABLA_PROVEEDOR
EXEC HARAKIRI.MIGRAR_TABLA_CLIENTE
EXEC HARAKIRI.MIGRAR_TABLA_MATERIAL

EXEC HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA
EXEC HARAKIRI.MIGRAR_TABLA_VENTA
EXEC HARAKIRI.MIGRAR_TABLA_MEDIO_ENVIO
EXEC HARAKIRI.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA
EXEC HARAKIRI.MIGRAR_TABLA_DESCUENTO_COMPRA

EXEC HARAKIRI.MIGRAR_TABLA_MARCA
EXEC HARAKIRI.MIGRAR_TABLA_CATEGORIA
EXEC HARAKIRI.MIGRAR_TABLA_TIPO_VARIANTE
EXEC HARAKIRI.MIGRAR_TABLA_VARIANTE
EXEC HARAKIRI.MIGRAR_TABLA_PRODUCTO
EXEC HARAKIRI.MIGRAR_TABLA_PRODUCTO_VARIANTE
/*EXEC HARAKIRI.MIGRAR_TABLA_VENTA_POR_PRODUCTO*/