USE GD2C2022
GO

-- BORRADO DE FKS
/*BORRO CONSTRAINS FK A LA TABLA  XXXX*/
IF OBJECT_ID('HARAKIRI.VENTA_CLIENTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT VENTA_CLIENTE_CODIGO
GO

-- BORRADO DE TABLAS

IF OBJECT_ID('HARAKIRI.NOMBRE_TABLA', 'U') IS NOT NULL
  DROP TABLE HARAKIRI.NOMBRE_TABLA
GO

-- BORRADO DE FUNCIONES

IF OBJECT_ID('HARAKIRI.NOMBRE_FUNCION') IS NOT NULL
	DROP FUNCTION HARAKIRI.NOMBRE_FUNCION
GO

-- BORRADO DE STORE PROCEDURES

IF OBJECT_ID('HARAKIRI.NOMBRE_PROCEDURE') IS NOT NULL
  DROP PROCEDURE HARAKIRI.NOMBRE_PROCEDURE
GO  

-- BORRADO DE ESQUEMA

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'HARAKIRI')
  DROP SCHEMA HARAKIRI
GO

-- CREACIÓN DE ESQUEMA

CREATE SCHEMA HARAKIRI
GO

-- CREACIÓN DE LAS TABLAS

CREATE TABLE HARAKIRI.NOMBRE_TABLA(
    PILOTO_CODIGO int IDENTITY(1,1) NOT NULL,
    PILOTO_NOMBRE nvarchar(50),
    PILOTO_APELLIDO nvarchar(50), 
    PILOTO_NACIONALIDAD nvarchar(50), 
    PILOTO_FECHA_NACIMIENTO datetime2(3), 
    AUTO_CODIGO int 
);
GO

-- CREACIÓN DE LAS PKS

ALTER TABLE HARAKIRI.TABLA ADD CONSTRAINT NOMBRE_PK PRIMARY KEY (NOMBRE_CAMPO_PK)
GO

-- CREACIÓN DE LAS FKS

ALTER TABLE HARAKIRI.TABLA ADD CONSTRAINT NOMBRE_FK FOREIGN KEY (NOMBRE_CAMPO) REFERENCES HARAKIRI.TABLA_REFERENCIADA
GO

-- CREACIÓN DE FUNCIONES

CREATE FUNCTION HARAKIRI.FUNCION(PARAMETROS)
RETURNS INT 
AS
BEGIN 
  
END 
GO 

-- CREACIÓN DE STORE PROCEDURES

CREATE PROCEDURE HARAKIRI.NOMBRE_PROCEDURE
AS
BEGIN 

  
END 
GO

-- EXECUTE DE STORE PROCEDURES

EXEC HARAKIRI.NOMBRE_PROCEDURE

------------------------
/*CREACION DE ESQUEMA*/

IF NOT EXISTS (SELECT * FROM sys.squemas WHERE name = 'HARAKIRI')

-----------------------
