USE GD2C2022
GO
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/


/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA MEDIO_ENVIO_POR_LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO
END
GO


/*BORRO CONSTRAINS FK A LA TABLA COMPRA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_MEDIO_DE_PAGO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_MEDIO_DE_PAGO_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_PROVEEDOR
END
GO

/*BORRO CONSTRAINS FK A LA TABLA DESCUENTO_COMPRA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA PROVEEDOR*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR DROP CONSTRAINT FK_PROVEEDOR_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA COMPRA_POR_PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO
/*BORRO CONSTRAINS FK A LA TABLA CLIENTE*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE DROP CONSTRAINT FK_CLIENTE_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON DROP CONSTRAINT FK_CUPON_CUPON_TIPO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON DROP CONSTRAINT FK_VENTA_POR_CUPON_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA DESCUENTO_POR_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA
END
GO

/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MARCA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MATERIAL
END
GO
/*BORRO CONSTRAINS FK A LA TABLA VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_CANAL
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_VENTA_POR_CUPON
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_MEDIO_DE_PAGO_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_CLIENTE
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD
END
GO


/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_CATEGORIA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_MATERIAL
END
GO


/*BORRO CONSTRAINS FK A LA TABLA PRODUCTO_VARIANTE*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_VARIANTE_PRODUCTO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_VARIANTE_VARIANTE
END
GO


/*BORRO CONSTRAINS FK A LA TABLA VARIANTE*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VARIANTE_TIPO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VARIANTE DROP CONSTRAINT FK_VARIANTE_TIPO_VARIANTE
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_POR_PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO DROP CONSTRAINT FK_VENTA_POR_PRODUCTO_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO DROP CONSTRAINT FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_POR_CUPON*/

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON DROP CONSTRAINT FK_VENTA_POR_CUPON_CUPON
END
GO
























-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('HARAKIRI.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.LOCALIDAD
	PRINT('Tabla HARAKIRI.LOCALIDAD eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVINCIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVINCIA
	PRINT('Tabla HARAKIRI.PROVINCIA eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVEEDOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVEEDOR
	PRINT('Tabla HARAKIRI.PROVEEDOR eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA
	PRINT('Tabla HARAKIRI.COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.CLIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CLIENTE
	PRINT('Tabla HARAKIRI.CLIENTE eliminada')
END

IF OBJECT_ID('HARAKIRI.MATERIAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MATERIAL
	PRINT('Tabla HARAKIRI.MATERIAL eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON_TIPO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON_TIPO
	PRINT('Tabla HARAKIRI.CUPON_TIPO eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON
	PRINT('Tabla HARAKIRI.CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.CANAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CANAL
	PRINT('Tabla HARAKIRI.CANAL eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA_POR_CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA_POR_CUPON
	PRINT('Tabla HARAKIRI.VENTA_POR_CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_CONCEPTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_CONCEPTO
	PRINT('Tabla HARAKIRI.DESCUENTO_CONCEPTO eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_POR_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_POR_VENTA
	PRINT('Tabla HARAKIRI.DESCUENTO_POR_VENTA eliminada')
END
IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_VENTA eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO eliminada')
END

IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_COMPRA
	PRINT('Tabla HARAKIRI.DESCUENTO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA_POR_PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	PRINT('Tabla HARAKIRI.COMPRA_POR_PRODUCTO eliminada')
END


IF OBJECT_ID('HARAKIRI.PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PRODUCTO
	PRINT('Tabla HARAKIRI.PRODUCTO eliminada')
END

IF OBJECT_ID('HARAKIRI.PRODUCTO_VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PRODUCTO_VARIANTE
	PRINT('Tabla HARAKIRI.PRODUCTO_VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VARIANTE
	PRINT('Tabla HARAKIRI.VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.CATEGORIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CATEGORIA
	PRINT('Tabla HARAKIRI.CATEGORIA eliminada')
END

IF OBJECT_ID('HARAKIRI.MARCA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MARCA
	PRINT('Tabla HARAKIRI.MARCA eliminada')
END

IF OBJECT_ID('HARAKIRI.TIPO_VARIANTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.TIPO_VARIANTE
	PRINT('Tabla HARAKIRI.TIPO_VARIANTE eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA_POR_PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA_POR_PRODUCTO
	PRINT('Tabla HARAKIRI.VENTA_POR_PRODUCTO eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA
	PRINT('Tabla HARAKIRI.VENTA eliminada')
END











/*
TODO
*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'HARAKIRI')
BEGIN
   DROP SCHEMA HARAKIRI
   PRINT('Esquema HARAKIRI borrado')
END
GO

USE GD2C2022
GO
----------------------------------------------------------------------------------------------------------
/*CREACION DE ESQUEMA*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'HARAKIRI')
BEGIN
    EXEC ('CREATE SCHEMA HARAKIRI')
	PRINT('Esquema HARAKIRI creado')
END
GO











USE GD2C2022
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PROVEEDOR') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PROVEEDOR (
		
        PROVEEDOR_CUIT nvarchar(50) NOT NULL,
        PROVEEDOR_LOCALIDAD_CODIGO decimal(18,0) NOT NULL, --FK A LOCALIDAD
        PROVEEDOR_RAZON_SOCIAL nvarchar(50) NOT NULL, 
        PROVEEDOR_DOMICILIO nvarchar(50) NOT NULL, 
        PROVEEDOR_MAIL nvarchar(50) NOT NULL
	)
	PRINT('Tabla HARAKIRI.PROVEEDOR creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.LOCALIDAD (
		
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_PROVINCIA_CODIGO decimal(18,0) NOT NULL,
        LOCALIDAD_NOMBRE NVARCHAR(255) NOT NULL,
        LOCALIDAD_CODIGO_POSTAL decimal(18,0) NOT NULL
	)
	PRINT('Tabla HARAKIRI.LOCALIDAD creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PROVINCIA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PROVINCIA (
		
        PROVINCIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        PROVINCIA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.PROVINCIA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.COMPRA (
		
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        COMPRA_MEDIO_DE_PAGO_CODIGO decimal(19,0), --FK
        PROVEEDOR_CUIT nvarchar(50), --FK
        COMPRA_FECHA date,
        COMPRA_TOTAL decimal(18,2)
	)
	PRINT('Tabla HARAKIRI.COMPRA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA (
		
        VENTA_CODIGO decimal(19,0) NOT NULL,
        VENTA_CANAL_CODIGO decimal(19,0),
        VENTA_CUPON_CODIGO nvarchar(255),
        VENTA_MEDIO_DE_PAGO_CODIGO decimal(19, 0),
        VENTA_CLIENTE_CODIGO decimal(19, 0),
        VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19, 0),
        VENTA_FECHA date,
        VENTA_TOTAL decimal(18, 2)
	)
	PRINT('Tabla HARAKIRI.VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_DE_PAGO_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA (

        MEDIO_DE_PAGO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_DE_PAGO_NOMBRE NVARCHAR(255) NOT NULL,
        MEDIO_DE_PAGO_COSTO decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_ENVIO_POR_LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD (

        MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL,
        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL,
        VENTA_ENVIO_PRECIO decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_ENVIO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_ENVIO (

        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_ENVIO_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CLIENTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CLIENTE (

	CLIENTE_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CLIENTE_NOMBRE nvarchar(255) NOT NULL,
        CLIENTE_APELLIDO nvarchar(255) NOT NULL ,
        CLIENTE_DNI decimal(18,0) NOT NULL,
        CLIENTE_DIRECCION nvarchar(255) NOT NULL,
        CLIENTE_TELEFONO decimal(18,0) NOT NULL,
        CLIENTE_MAIL nvarchar(255) NOT NULL,
        CLIENTE_FECHA_NAC date NOT NULL,
        CLIENTE_LOCALIDAD_CODIGO decimal(18,0) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CLIENTE creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MATERIAL') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MATERIAL (
                
	MATERIAL_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MATERIAL_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.MATERIAL creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CUPON_TIPO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CUPON_TIPO (

        CUPON_TIPO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CUPON_TIPO_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CUPON_TIPO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CUPON') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CUPON (

        CUPON_CODIGO nvarchar(255) NOT NULL,
        CUPON_TIPO_CODIGO decimal(19,0),
        CUPON_FECHA_DESDE date,
        CUPON_FECHA_HASTA date,
        CUPON_IMPORTE decimal(18,2),
        CUPON_VALOR decimal(18,2)
        )
	PRINT('Tabla HARAKIRI.CUPON creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CANAL') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CANAL (

        CANAL_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CANAL_NOMBRE nvarchar(2555),
        CANAL_COSTO decimal(18,2)
        )
	PRINT('Tabla HARAKIRI.CANAL creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA_POR_CUPON') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA_POR_CUPON (
                
        CUPON_CODIGO nvarchar(255) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        CUPON_IMPORTE decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.VENTA_POR_CUPON creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_CONCEPTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_CONCEPTO (
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_NOMBRE nvarchar(255) NOT NULL
        )
	PRINT('Tabla HARAKIRI.DESCUENTO_CONCEPTO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_POR_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_POR_VENTA (
        DESCUENTO_POR_VENTA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        DESCUENTO_IMPORTE decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.DESCUENTO_POR_VENTA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MEDIO_DE_PAGO_COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA (

        MEDIO_DE_PAGO_COMPRA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_COMPRA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].DESCUENTO_COMPRA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.DESCUENTO_COMPRA (

        DESCUENTO_COMPRA_CODIGO decimal(19,0) NOT NULL,
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        DESCUENTO_COMPRA_VALOR decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.DESCUENTO_COMPRA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].COMPRA_POR_PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.COMPRA_POR_PRODUCTO (

        COMPRA_NUMERO decimal(19,0) NOT NULL,
        PRODUCTO_VARIANTE_CODIGO NVARCHAR(50) NOT NULL,
        PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
        PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
	)
	PRINT('Tabla HARAKIRI.COMPRA_POR_PRODUCTO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].CATEGORIA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.CATEGORIA (
                
	CATEGORIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        CATEGORIA_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.CATEGORIA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].MARCA') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.MARCA (
                
	MARCA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MARCA_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.MARCA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PRODUCTO (
	PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_MARCA_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_MATERIAL_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_CATEGORIA_CODIGO decimal(18,0) NOT NULL ,
        PRODUCTO_NOMBRE nvarchar(50)  NOT NULL ,
        PRODUCTO_DESCRIPCION nvarchar(50) NOT NULL
        )
	PRINT('Tabla HARAKIRI.PRODUCTO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].PRODUCTO_VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.PRODUCTO_VARIANTE (
	PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        VARIANTE_CODIGO decimal (18,0) NOT NULL,
        PRECIO_ACTUAL_COMPRA decimal(18,2) NOT NULL,
        PRECIO_ACTUAL_VENTA decimal(18,2)  
        )
	PRINT('Tabla HARAKIRI.PRODUCTO_VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VARIANTE (
	VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1) ,
        VARIANTE_TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL,
        VARIANTE_NOMBRE nvarchar (50) NOT NULL,
     
        )
	PRINT('Tabla HARAKIRI.VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].TIPO_VARIANTE') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.TIPO_VARIANTE (
	TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1) ,
        TIPO_VARIANTE_VALOR nvarchar (50) NOT NULL,
     
        )
	PRINT('Tabla HARAKIRI.TIPO_VARIANTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[HARAKIRI].VENTA_POR_PRODUCTO') AND type = 'U')
BEGIN
	CREATE TABLE HARAKIRI.VENTA_POR_PRODUCTO (
                
        PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
        PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
        )
	PRINT('Tabla HARAKIRI.VENTA_POR_PRODUCTO creada')
END
GO














----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.LOCALIDAD agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PROVINCIA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.PROVINCIA
	ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (PROVINCIA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.PROVINCIA agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA MEDIO_DE_PAGO_VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA
	ADD CONSTRAINT PK_MEDIO_DE_PAGO_VENTA PRIMARY KEY (MEDIO_DE_PAGO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MEDIO_DE_PAGO_VENTA agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA MEDIO_DE_ENVIO_POR_LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT PK_MEDIO_ENVIO_POR_LOCALIDAD PRIMARY KEY (MEDIO_ENVIO_POR_LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA MEDIO_DE_ENVIO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO
	ADD CONSTRAINT PK_MEDIO_ENVIO PRIMARY KEY (MEDIO_ENVIO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MEDIO_ENVIO agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA MEDIO_DE_PAGO_COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA
	ADD CONSTRAINT PK_MEDIO_DE_PAGO_COMPRA PRIMARY KEY (MEDIO_DE_PAGO_COMPRA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA DESCUENTO_COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA
	ADD CONSTRAINT PK_DESCUENTO_COMPRA PRIMARY KEY (DESCUENTO_COMPRA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.DESCUENTO_COMPRA agregada')
END
GO

/* AGREGANDO CONSTRAINT PK A LA TABLA COMPRA_POR_PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRA_POR_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT PK_COMPRA_POR_PRODUCTO PRIMARY KEY (COMPRA_NUMERO)
	PRINT('Primary key de la tabla HARAKIRI.COMPRA_POR_PRODUCTO agregada')
END
GO
/*AGREGANDO CONSTRAINT PK A LA TABLA COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT PK_COMPRA PRIMARY KEY (COMPRA_NUMERO)
	PRINT('Primary key de la tabla HARAKIRI.COMPRA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CLIENTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CLIENTE agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA MATERIAL*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.MATERIAL
	ADD CONSTRAINT PK_MATERIAL PRIMARY KEY (MATERIAL_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MATERIAL agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CUPON_TIPO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON_TIPO
	ADD CONSTRAINT PK_CUPON_TIPO PRIMARY KEY (CUPON_TIPO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CUPON_TIPO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.CUPON
	ADD CONSTRAINT PK_CUPON PRIMARY KEY (CUPON_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CUPON agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CANAL*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.CANAL
	ADD CONSTRAINT PK_CANAL PRIMARY KEY (CANAL_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CANAL agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA_POR_CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT PK_VENTA_POR_CUPON PRIMARY KEY (CUPON_CODIGO, VENTA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.VENTA_POR_CUPON agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA DESCUENTO_CONCEPTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_CONCEPTO
	ADD CONSTRAINT PK_DESCUENTO_CONCEPTO PRIMARY KEY (DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.DESCUENTO_CONCEPTO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA DESCUENTO_POR_VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_POR_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT PK_DESCUENTO_POR_VENTA PRIMARY KEY (DESCUENTO_POR_VENTA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.DESCUENTO_POR_VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PROVEEDOR*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR
	ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (PROVEEDOR_CUIT)
	PRINT('Primary key de la tabla HARAKIRI.PROVEEDOR agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.PRODUCTO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PRODUCTO_VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE
	ADD CONSTRAINT PK_PRODUCTO_VARIANTE PRIMARY KEY (PRODUCTO_VARIANTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.PRODUCTO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VARIANTE
	ADD CONSTRAINT PK_VARIANTE PRIMARY KEY (VARIANTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA TIPO_VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.TIPO_VARIANTE
	ADD CONSTRAINT PK_TIPO_VARIANTE PRIMARY KEY (TIPO_VARIANTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.TIPO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA_POR_PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA_POR_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO
	ADD CONSTRAINT PK_VENTA_POR_PRODUCTO PRIMARY KEY (PRODUCTO_VARIANTE_CODIGO,VENTA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.VENTA_POR_PRODUCTO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT PK_VENTA PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA MARCA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.MARCA
	ADD CONSTRAINT PK_MARCA PRIMARY KEY (MARCA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MARCA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CATEGORIA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.CATEGORIA
	ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATEGORIA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CATEGORIA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA_POR_CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.CATEGORIA
	ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATEGORIA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CATEGORIA agregada')
END
GO







----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT FK PARA LAS TABLAS DE LA BASE DE DATOS */

/*AGREGANDO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD
	ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY(LOCALIDAD_PROVINCIA_CODIGO) REFERENCES HARAKIRI.PROVINCIA(PROVINCIA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.LOCALIDAD y HARAKIRI.PROVINCIA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA MEDIO_ENVIO_POR_LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD y HARAKIRI.LOCALIDAD agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO FOREIGN KEY(MEDIO_ENVIO_CODIGO) REFERENCES HARAKIRI.MEDIO_ENVIO(MEDIO_ENVIO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD y HARAKIRI.MEDIO_ENVIO agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT FK_COMPRA_MEDIO_DE_PAGO FOREIGN KEY(COMPRA_MEDIO_DE_PAGO_CODIGO) REFERENCES HARAKIRI.MEDIO_DE_PAGO_COMPRA(MEDIO_DE_PAGO_COMPRA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA y HARAKIRI.MEDIO_DE_PAGO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY(PROVEEDOR_CUIT) REFERENCES HARAKIRI.PROVEEDOR(PROVEEDOR_CUIT)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA y HARAKIRI.PROVEEDOR agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON
	ADD CONSTRAINT FK_CUPON_CUPON_TIPO FOREIGN KEY(CUPON_TIPO_CODIGO) REFERENCES HARAKIRI.CUPON_TIPO(CUPON_TIPO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.CUPON y HARAKIRI.CUPON_TIPO agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA_POR_CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_CUPON FOREIGN KEY(CUPON_CODIGO) REFERENCES HARAKIRI.CUPON(CUPON_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_CUPON y HARAKIRI.CUPON agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_CUPON y HARAKIRI.VENTA agregada')
END
GO


/*AGREGANDO CONSTRAINS FK A LA TABLA DESCUENTO_POR_VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO FOREIGN KEY(DESCUENTO_CONCEPTO_CODIGO) REFERENCES HARAKIRI.DESCUENTO_CONCEPTO(DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_POR_VENTA y HARAKIRI.DESCUENTO_CONCEPTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_POR_VENTA y HARAKIRI.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA DESCUENTO_COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA
	ADD CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES HARAKIRI.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas HARAKIRI.DESCUENTO_COMPRA y HARAKIRI.COMPRA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA COMPRA_POR_PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES HARAKIRI.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA_POR_PRODUCTO y HARAKIRI.COMPRA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES HARAKIRI.PRODUCTO_VARIANTE (PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.COMPRA_POR_PRODUCTO y HARAKIRI.PRODUCTO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PROVEEDOR*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR
	ADD CONSTRAINT FK_PROVEEDOR_LOCALIDAD FOREIGN KEY(PROVEEDOR_LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.LOCALIDAD y HARAKIRI.PROVEEDOR agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA CLIENTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE
	ADD CONSTRAINT FK_CLIENTE_LOCALIDAD FOREIGN KEY(CLIENTE_LOCALIDAD_CODIGO) REFERENCES HARAKIRI.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.CLIENTE y HARAKIRI.LOCALIDAD agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PRODUCTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY(PRODUCTO_MARCA_CODIGO) REFERENCES HARAKIRI.MARCA(MARCA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.MARCA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_CATEGORIA')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY(PRODUCTO_CATEGORIA_CODIGO) REFERENCES HARAKIRI.CATEGORIA(CATEGORIA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.CATEGORIA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MATERIAL FOREIGN KEY(PRODUCTO_MATERIAL_CODIGO) REFERENCES HARAKIRI.MATERIAL(MATERIAL_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO y HARAKIRI.MATERIAL agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA PRODUCTO_VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_PRODUCTO')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_PRODUCTO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES HARAKIRI.PRODUCTO(PRODUCTO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO_VARIANTE y HARAKIRI.PRODUCTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_VARIANTE FOREIGN KEY(VARIANTE_CODIGO) REFERENCES HARAKIRI.VARIANTE(VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.PRODUCTO_VARIANTE y HARAKIRI.VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VARIANTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VARIANTE_TIPO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VARIANTE
	ADD CONSTRAINT FK_VARIANTE_TIPO_VARIANTE FOREIGN KEY(VARIANTE_TIPO_VARIANTE_CODIGO) REFERENCES HARAKIRI.TIPO_VARIANTE(TIPO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VARIANTE y HARAKIRI.TIPO_VARIANTE agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA_POR_PRODUCTO*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES HARAKIRI.PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_PRODUCTO y HARAKIRI.PRODUCTO_VARIANTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES HARAKIRI.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA_POR_PRODUCTO y HARAKIRI.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_CANAL FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES HARAKIRI.CANAL(CANAL_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CANAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_VENTA_POR_CUPON FOREIGN KEY(VENTA_CUPON_CODIGO) REFERENCES HARAKIRI.VENTA_POR_CUPON(CUPON_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CUPON agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_DE_PAGO_VENTA FOREIGN KEY(VENTA_MEDIO_DE_PAGO_CODIGO) REFERENCES HARAKIRI.MEDIO_DE_PAGO_VENTA(MEDIO_DE_PAGO_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.MEDIO_DE_PAGO_VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY(VENTA_CLIENTE_CODIGO) REFERENCES HARAKIRI.CLIENTE(CLIENTE_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.CLIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD(MEDIO_ENVIO_POR_LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas HARAKIRI.VENTA y HARAKIRI.LOCALIDAD agregada')
END
GO

