USE GD2C2022
GO
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/


/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMBRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMBRA
END
GO


IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO
/*
IF OBJECT_ID('HARAKIRI.VENTA_CLIENTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT VENTA_CLIENTE_CODIGO
GO


IF OBJECT_ID('HARAKIRI.COMPRA_MEDIO_DE_PAGO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT COMPRA_MEDIO_DE_PAGO_CODIGO
GO

IF OBJECT_ID('HARAKIRI.PROVEEDOR_CUIT', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT PROVEEDOR_CUIT
GO

*/

/*
TODO
*/
-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('HARAKIRI.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.LOCALIDAD
	PRINT('Tabla HARAKIRI.LOCALIDAD eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVINCIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVINCIA
	PRINT('Tabla HARAKIRI.PROVINCIA eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVEEDOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVEEDOR
	PRINT('Tabla HARAKIRI.PROVEEDOR eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA
	PRINT('Tabla HARAKIRI.COMPRA eliminada')
END


/*
TODO
*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'HARAKIRI')
BEGIN
   DROP SCHEMA HARAKIRI
   PRINT('Esquema HARAKIRI borrado')
END
GO