USE GD2C2022
GO
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/


/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA MEDIO_ENVIO_POR_LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO
END
GO


/*BORRO CONSTRAINS FK A LA TABLA COMPRA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_MEDIO_DE_PAGO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_MEDIO_DE_PAGO_COMPRA
END
GO



IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT FK_COMPRA_PROVEEDOR
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.PROVEEDOR DROP CONSTRAINT FK_PROVEEDOR_LOCALIDAD
END
GO
/*BORRO CONSTRAINS FK A LA TABLA COMPRA_POR_PRODUCTO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA
END
GO


IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO DROP CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE
END
GO
/*BORRO CONSTRAINS FK A LA TABLA CLIENTE*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE DROP CONSTRAINT FK_CLIENTE_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON DROP CONSTRAINT FK_CUPON_CUPON_TIPO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA_CUPON*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_CUPON DROP CONSTRAINT FK_VENTA_POR_CUPON_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_CUPON DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

/*BORRO CONSTRAINS FK A LA TABLA DESCUENTO_POR_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA DROP CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA
END
GO

/*
IF OBJECT_ID('HARAKIRI.VENTA_CLIENTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.VENTA DROP CONSTRAINT VENTA_CLIENTE_CODIGO
GO


IF OBJECT_ID('HARAKIRI.COMPRA_MEDIO_DE_PAGO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT COMPRA_MEDIO_DE_PAGO_CODIGO
GO

IF OBJECT_ID('HARAKIRI.PROVEEDOR_CUIT', 'F') IS NOT NULL
  ALTER TABLE HARAKIRI.COMPRA DROP CONSTRAINT PROVEEDOR_CUIT
GO

*/

/*
TODO
*/
-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('HARAKIRI.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.LOCALIDAD
	PRINT('Tabla HARAKIRI.LOCALIDAD eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVINCIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVINCIA
	PRINT('Tabla HARAKIRI.PROVINCIA eliminada')
END

IF OBJECT_ID('HARAKIRI.PROVEEDOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.PROVEEDOR
	PRINT('Tabla HARAKIRI.PROVEEDOR eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA
	PRINT('Tabla HARAKIRI.COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.CLIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CLIENTE
	PRINT('Tabla HARAKIRI.CLIENTE eliminada')
END

IF OBJECT_ID('HARAKIRI.MATERIAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MATERIAL
	PRINT('Tabla HARAKIRI.MATERIAL eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON_TIPO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON_TIPO
	PRINT('Tabla HARAKIRI.CUPON_TIPO eliminada')
END

IF OBJECT_ID('HARAKIRI.CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CUPON
	PRINT('Tabla HARAKIRI.CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.CANAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.CANAL
	PRINT('Tabla HARAKIRI.CANAL eliminada')
END

IF OBJECT_ID('HARAKIRI.VENTA_POR_CUPON', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.VENTA_POR_CUPON
	PRINT('Tabla HARAKIRI.VENTA_POR_CUPON eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_CONCEPTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_CONCEPTO
	PRINT('Tabla HARAKIRI.DESCUENTO_CONCEPTO eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_POR_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_POR_VENTA
	PRINT('Tabla HARAKIRI.DESCUENTO_POR_VENTA eliminada')
END
IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_VENTA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_VENTA eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO_POR_LOCALIDAD eliminada')
END


IF OBJECT_ID('HARAKIRI.MEDIO_ENVIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_ENVIO
	PRINT('Tabla HARAKIRI.MEDIO_ENVIO eliminada')
END

IF OBJECT_ID('HARAKIRI.MEDIO_DE_PAGO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.MEDIO_DE_PAGO_COMPRA
	PRINT('Tabla HARAKIRI.MEDIO_DE_PAGO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.DESCUENTO_COMPRA', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.DESCUENTO_COMPRA
	PRINT('Tabla HARAKIRI.DESCUENTO_COMPRA eliminada')
END

IF OBJECT_ID('HARAKIRI.COMPRA_POR_PRODUCTO', 'U') IS NOT NULL
BEGIN
	DROP TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	PRINT('Tabla HARAKIRI.COMPRA_POR_PRODUCTO eliminada')
END


/*
TODO
*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'HARAKIRI')
BEGIN
   DROP SCHEMA HARAKIRI
   PRINT('Esquema HARAKIRI borrado')
END
GO