
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA LOCALIDAD*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_LOCALIDAD')
BEGIN
	ALTER TABLE HARAKIRI.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.LOCALIDAD agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PROVINCIA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVINCIA')
BEGIN
	ALTER TABLE HARAKIRI.PROVINCIA
	ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (PROVINCIA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.PROVINCIA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA COMPRA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRA')
BEGIN
	ALTER TABLE HARAKIRI.COMPRA
	ADD CONSTRAINT PK_COMPRA PRIMARY KEY (COMPRA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.COMPRA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CLIENTE*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CLIENTE')
BEGIN
	ALTER TABLE HARAKIRI.CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CLIENTE agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA MATERIAL*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MATERIAL')
BEGIN
	ALTER TABLE HARAKIRI.MATERIAL
	ADD CONSTRAINT PK_MATERIAL PRIMARY KEY (MATERIAL_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.MATERIAL agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CUPON_TIPO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON_TIPO')
BEGIN
	ALTER TABLE HARAKIRI.CUPON_TIPO
	ADD CONSTRAINT PK_CUPON_TIPO PRIMARY KEY (CUPON_TIPO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CUPON_TIPO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON')
BEGIN
	ALTER TABLE HARAKIRI.CUPON
	ADD CONSTRAINT PK_CUPON PRIMARY KEY (CUPON_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CUPON agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA CANAL*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CANAL')
BEGIN
	ALTER TABLE HARAKIRI.CANAL
	ADD CONSTRAINT PK_CANAL PRIMARY KEY (CANAL_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.CANAL agregada')
END
GO

--
/*
ENRIQUE SAMUEL ONTIVEROS VEIZAGA17:46
/* AGREGANDO CONSTRAINT PK A LA TABLA COMPRA_POR_PRODUCTO*/
/*
BEGIN
	ALTER TABLE HARAKIRI.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT PK_COMPRA_POR_PRODUCTO PRIMARY KEY (COMPRA_NUMERO, PRODUCTO_VARIANTE_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.COMPRA_POR_PRODUCTO agregada')
END
GO
*/
--

/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA_POR_CUPON*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA_POR_CUPON_CODIGO')
BEGIN
	ALTER TABLE HARAKIRI.VENTA_POR_CUPON
	ADD CONSTRAINT PK_VENTA_POR_CUPON_CODIGO PRIMARY KEY (CUPON_CODIGO, VENTA_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.VENTA_POR_CUPON agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA DESCUENTO_CONCEPTO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_CONCEPTO
	ADD CONSTRAINT PK_DESCUENTO_CONCEPTO PRIMARY KEY (DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.DESCUENTO_CONCEPTO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA DESCUENTO_POR_VENTA*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_POR_VENTA')
BEGIN
	ALTER TABLE HARAKIRI.DESCUENTO_POR_VENTA
	ADD CONSTRAINT PK_DESCUENTO_POR_VENTA PRIMARY KEY (DESCUENTO_CODIGO)
	PRINT('Primary key de la tabla HARAKIRI.DESCUENTO_POR_VENTA agregada')
END
GO
