-- Acá van los create de los procedures y los EXEC de ellos
--CREACION DE PROCEDURES

CREATE PROCEDURE HARAKIRI.MIGRAR_PROVINCIA
AS
BEGIN 
  INSERT INTO HARAKIRI.PROVINCIA (PROVINCIA_NOMBRE)
  SELECT DISTINCT CLIENTE_PROVINCIA
  FROM GD_ESQUEMA.MAESTRA
  WHERE CLIENTE_PROVINCIA IS NOT NULL
  UNION
  SELECT DISTINCT PROVEEDOR_PROVINCIA
  FROM GD_ESQUEMA.MAESTRA
  WHERE PROVEEDOR_PROVINCIA IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PROVINCIA)
PRINT('Datos migrados a la tabla HARAKIRI.PROVINCIA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE HARAKIRI.MIGRAR_LOCALIDAD
AS
BEGIN 
INSERT INTO HARAKIRI.LOCALIDAD (LOCALIDAD_PROVINCIA_CODIGO, LOCALIDAD_NOMBRE, LOCALIDAD_CODIGO_POSTAL)

  SELECT DISTINCT P.PROVINCIA_CODIGO, MA.CLIENTE_LOCALIDAD, MA.CLIENTE_CODIGO_POSTAL
  FROM gd_esquema.Maestra MA JOIN HARAKIRI.PROVINCIA P ON MA.CLIENTE_PROVINCIA = P.PROVINCIA_NOMBRE
  UNION
  SELECT DISTINCT P.PROVINCIA_CODIGO, MA.PROVEEDOR_LOCALIDAD, MA.PROVEEDOR_CODIGO_POSTAL
  FROM gd_esquema.Maestra MA JOIN HARAKIRI.PROVINCIA P ON MA.PROVEEDOR_PROVINCIA = P.PROVINCIA_NOMBRE

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.LOCALIDAD)
PRINT('Datos migrados a la tabla HARAKIRI.LOCALIDAD. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE HARAKIRI.MIGRAR_MATERIAL
AS
BEGIN 
  INSERT INTO HARAKIRI.MATERIAL (MATERIAL_NOMBRE)
  SELECT DISTINCT PRODUCTO_MATERIAL
  FROM GD_ESQUEMA.MAESTRA
  WHERE PRODUCTO_MATERIAL IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MATERIAL)
PRINT('Datos migrados a la tabla HARAKIRI.MATERIAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE HARAKIRI.MIGRAR_CLIENTE
AS
BEGIN 
  INSERT INTO HARAKIRI.CLIENTE (CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, CLIENTE_LOCALIDAD_CODIGO)
  SELECT DISTINCT CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, L.LOCALIDAD_CODIGO
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.LOCALIDAD L ON MA.CLIENTE_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.CLIENTE_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
  WHERE CLIENTE_NOMBRE IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.MATERIAL)
PRINT('Datos migrados a la tabla HARAKIRI.MATERIAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE HARAKIRI.MIGRAR_PROVEEDOR
AS
BEGIN 
  INSERT INTO HARAKIRI.PROVEEDOR (PROVEEDOR_CUIT, PROVEEDOR_LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL)
  SELECT DISTINCT PROVEEDOR_CUIT, L.LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.LOCALIDAD L ON MA.PROVEEDOR_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.PROVEEDOR_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
  WHERE PROVEEDOR_CUIT IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PROVEEDOR)
PRINT('Datos migrados a la tabla HARAKIRI.PROVEEDOR. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE HARAKIRI.MIGRAR_COMPRA
AS
BEGIN 
  INSERT INTO HARAKIRI.COMPRA (COMPRA_NUMERO, COMPRA_MEDIO_DE_PAGO_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL)
  SELECT DISTINCT COMPRA_NUMERO, MPC.MEDIO_DE_PAGO_COMPRA_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL
  FROM GD_ESQUEMA.MAESTRA MA JOIN HARAKIRI.MEDIO_DE_PAGO_COMPRA MPC ON MA.COMPRA_MEDIO_PAGO = MPC.MEDIO_DE_PAGO_COMPRA_NOMBRE
  WHERE COMPRA_NUMERO IS NOT NULL

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.COMPRA)
PRINT('Datos migrados a la tabla HARAKIRI.COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

EXEC HARAKIRI.MIGRAR_PROVINCIA
EXEC HARAKIRI.MIGRAR_LOCALIDAD
EXEC HARAKIRI.MIGRAR_COMPRA
EXEC HARAKIRI.MIGRAR_PROVEEDOR
EXEC HARAKIRI.MIGRAR_CLIENTE
EXEC HARAKIRI.MIGRAR_MATERIAL