CREATE TABLE HARAKIRI.BI_HECHO_VENTA_PRODUCTO(
    VENTA_PRODUCTO_CODIGO decimal(19,0) not null,
    EDAD_CODIGO decimal(19,0),
    TIEMPO_CODIGO decimal(19,0),
    PROVINCIA_CODIGO decimal(18,0),
    CANAL_CODIGO decimal(19,0),
    MEDIO_DE_PAGO_CODIGO decimal(19,0),
    CATEGORIA_CODIGO decimal(18,0),
    PRODUCTO_CODIGO nvarchar(50),
    MEDIO_ENVIO_CODIGO decimal(19,0),
    VENTA_ENVIO_PRECIO decimal(18,2),
    PRODUCTO_PRECIO_TOTAL decimal(18,2),
    VENTA_CODIGO decimal(19,0)
);  
GO

CREATE TABLE HARAKIRI.BI_PROVINCIA(
    PROVINCIA_CODIGO decimal(18,0) not null,
    PROVINCIA_NOMBRE nvarchar(255)
);  
GO

CREATE TABLE HARAKIRI.BI_MEDIO_DE_PAGO(
    MEDIO_DE_PAGO_CODIGO decimal(19,0) not null,
    MEDIO_DE_PAGO_NOMBRE nvarchar(255),
    MEDIO_DE_PAGO_COSTO decimal(19,2)
);
GO

CREATE TABLE HARAKIRI.BI_MEDIO_DE_ENVIO(
    MEDIO_ENVIO_CODIGO decimal(19,0) not null,
    MEDIO_ENVIO_NOMBRE nvarchar(255),
);
GO

CREATE TABLE HARAKIRI.BI_TIPO_DE_DESCUENTO(
    TIPO_DESCUENTO_CODIGO decimal(19,0) not null,
    TIPO_DESCUENTO_NOMBRE nvarchar(50),
);
GO


CREATE TABLE HARAKIRI.BI_VENTA(
    CANAL_CODIGO decimal(19,0) not null,
    CANA_NOMBRE nvarchar(50),
    CANAL_CODIGO decimal(18,2) not null,
);
GO

CREATE TABLE HARAKIRI.BI_PROVEEDOR(
    PROVEEDOR_CIUT decimal(18,0) not null,
    PROVEEDOR_RAZON_SOCIAL nvarchar(255),
);
GO