----------------------------------------------------------------------------------------------------------
/* MIGRACION DE TABLAS */

/* MIGRACION DE TABLA BI_TIEMPO */




IF (SELECT COUNT(*) FROM HARAKIRI.BI_TIEMPO) = 0
BEGIN
	INSERT INTO HARAKIRI.BI_TIEMPO(TIEMPO_ANIO, TIEMPO_MES)
	(
		SELECT YEAR(V.VENTA_FECHA) AS TIEMPO_ANIO, MONTH(V.VENTA_FECHA) AS TIEMPO_MES
		FROM HARAKIRI.VENTA AS V
		GROUP BY YEAR(V.VENTA_FECHA), MONTH(V.VENTA_FECHA)

		UNION
 	    SELECT YEAR(C.COMPRA_FECHA) AS TIEMPO_ANIO, MONTH(C.COMPRA_FECHA) AS TIEMPO_MES
		FROM HARAKIRI.COMPRA AS C
		GROUP BY YEAR(C.COMPRA_FECHA), MONTH(C.COMPRA_FECHA)

	)
END
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.BI_TIEMPO)
PRINT('Datos migrados a la tabla HARAKIRI.BI_TIEMPO. Nuevas filas: ' + @CANTIDAD_REGISTROS)





/*MIGRACION TABLA RANGO_EDAD*/
INSERT INTO HARAKIRI.BI_RANGO_EDAD(EDAD_CATEGORIA)
	VALUES('<25')
INSERT INTO HARAKIRI.BI_RANGO_EDAD(EDAD_CATEGORIA)
	VALUES('25 - 35')
INSERT INTO HARAKIRI.BI_RANGO_EDAD(EDAD_CATEGORIA)
	VALUES('35 - 55')
INSERT INTO HARAKIRI.BI_RANGO_EDAD(EDAD_CATEGORIA)
	VALUES('>55')


