USE GD2C2022
GO

/*Creación de vistas*/
IF OBJECT_ID('HARAKIRI.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES') IS NOT NULL
BEGIN
	DROP VIEW HARAKIRI.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES
    PRINT('Vista HARAKIRI.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES eliminado')
END
GO

CREATE VIEW HARAKIRI.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES
AS
SELECT  E.EDAD_CATEGORIA,T.TIEMPO_ANIO,T.TIEMPO_MES,vp.CATEGORIA_CODIGO,COUNT(vp.CATEGORIA_CODIGO)  as [VECES_VENDIDA_CATEGORIA]
FROM HARAKIRI.BI_HECHO_VENTA_PRODUCTO VP 
JOIN HARAKIRI.BI_CATEGORIA C ON C.CATEGORIA_CODIGO = VP.CATEGORIA_CODIGO
JOIN HARAKIRI.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
JOIN HARAKIRI.BI_RANGO_EDAD E ON VP.EDAD_CODIGO = E.EDAD_CODIGO
WHERE vp.CATEGORIA_CODIGO in(SELECT TOP 5 vp.CATEGORIA_CODIGO FROM HARAKIRI.BI_HECHO_VENTA_PRODUCTO vp	GROUP BY vp.CATEGORIA_CODIGO ORDER BY COUNT(DISTINCT vp.CATEGORIA_CODIGO) DESC)
GROUP BY  E.EDAD_CATEGORIA,T.TIEMPO_ANIO,T.TIEMPO_MES,vp.CATEGORIA_CODIGO
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES)
PRINT('View TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES creada. Cant filas: ' + @CANTIDAD_REGISTROS)

---vista4 --------

IF OBJECT_ID('HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES') IS NOT NULL
BEGIN
	DROP VIEW HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES
    PRINT('Vista HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES eliminado')
END
GO


CREATE VIEW HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES
AS
SELECT SUM(V.VENTA_TOTAL-MDP.MEDIO_DE_PAGO_COSTO) AS INGRESOS_TOTALES , T.TIEMPO_ANIO , T.TIEMPO_MES ,MDP.MEDIO_DE_PAGO_NOMBRE
FROM HARAKIRI.BI_HECHO_VENTA_PRODUCTO VP 
JOIN HARAKIRI.BI_MEDIO_DE_PAGO MDP ON MDP.MEDIO_DE_PAGO_CODIGO = VP.MEDIO_DE_PAGO_CODIGO
JOIN HARAKIRI.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO
JOIN HARAKIRI.BI_VENTA V ON V.VENTA_CODIGO = VP.VENTA_CODIGO
GROUP BY T.TIEMPO_ANIO , T.TIEMPO_MES,MDP.MEDIO_DE_PAGO_NOMBRE 
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES)
PRINT('View HARAKIRI.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES creada. Cant filas: ' + @CANTIDAD_REGISTROS)

IF OBJECT_ID('HARAKIRI.PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW HARAKIRI.PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL
    PRINT('Vista HARAKIRI.PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL eliminada')
END
GO

CREATE VIEW HARAKIRI.PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL
AS
SELECT TIEMPO_ANIO, PRODUCTO_NOMBRE, PORCENTAJE_RENTABILIDAD FROM (
SELECT T.TIEMPO_ANIO, P.PRODUCTO_NOMBRE, SUM(HVP.PRODUCTO_PRECIO_TOTAL) AS VENTA_TOTAL_PRODUCTO, SUM(HCP.PRODUCTO_CANTIDAD * HCP.PRODUCTO_PRECIO_UNITARIO) AS COMPRA_TOTAL_PRODUCTO, ((SUM(HVP.PRODUCTO_PRECIO_TOTAL) - SUM(HCP.PRODUCTO_CANTIDAD * HCP.PRODUCTO_PRECIO_UNITARIO))/SUM(HVP.PRODUCTO_PRECIO_TOTAL)) * 100 AS PORCENTAJE_RENTABILIDAD, ROW_NUMBER() OVER (PARTITION BY T.TIEMPO_ANIO ORDER BY ((SUM(HVP.PRODUCTO_PRECIO_TOTAL) - SUM(HCP.PRODUCTO_CANTIDAD * HCP.PRODUCTO_PRECIO_UNITARIO))/SUM(HVP.PRODUCTO_PRECIO_TOTAL)) * 100 DESC) AS TOP_MAYOR_RENTABILIDAD
FROM HARAKIRI.BI_HECHO_VENTA_PRODUCTO HVP
JOIN HARAKIRI.BI_PRODUCTO P ON P.PRODUCTO_CODIGO = HVP.PRODUCTO_CODIGO
JOIN HARAKIRI.BI_HECHO_COMPRA_PRODUCTO HCP ON HCP.PRODUCTO_CODIGO = P.PRODUCTO_CODIGO
JOIN HARAKIRI.BI_TIEMPO T ON T.TIEMPO_CODIGO = HVP.TIEMPO_CODIGO OR T.TIEMPO_CODIGO = HCP.TIEMPO_CODIGO
GROUP BY T.TIEMPO_ANIO, P.PRODUCTO_NOMBRE
) RENTABILIDADES
WHERE TOP_MAYOR_RENTABILIDAD <=5
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL)
PRINT('View PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL creada. Cant filas: ' + @CANTIDAD_REGISTROS)



IF OBJECT_ID('HARAKIRI.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES') IS NOT NULL
BEGIN
	DROP VIEW HARAKIRI.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES
    PRINT('Vista HARAKIRI.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES eliminado')
END
GO

CREATE VIEW HARAKIRI.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES
AS
SELECT  T.TIEMPO_ANIO,T.TIEMPO_MES,C.CANAL_NOMBRE,TD.TIPO_DESCUENTO_NOMBRE,SUM(VD.DESCUENTO_IMPORTE) AS [Importe Total]
FROM HARAKIRI.BI_HECHO_VENTA_DESCUENTO VD 
JOIN HARAKIRI.BI_CANAL_VENTA C ON C.CANAL_CODIGO = VD.CANAL_CODIGO
JOIN HARAKIRI.BI_TIEMPO T ON VD.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
JOIN HARAKIRI.BI_TIPO_DE_DESCUENTO TD ON VD.TIPO_DESCUENTO_CODIGO = TD.TIPO_DESCUENTO_CODIGO
GROUP BY  T.TIEMPO_ANIO,T.TIEMPO_MES,C.CANAL_NOMBRE,TD.TIPO_DESCUENTO_NOMBRE
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES)
PRINT('View IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES creada. Cant filas: ' + @CANTIDAD_REGISTROS)



IF OBJECT_ID('HARAKIRI.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW HARAKIRI.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL
    PRINT('Vista HARAKIRI.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL eliminado')
END
GO

CREATE VIEW HARAKIRI.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL
AS
SELECT
    P.PROVEEDOR_RAZON_SOCIAL,
    T.TIEMPO_ANIO,
    (
        MAX(CP.PRODUCTO_PRECIO_UNITARIO) - 
        MIN(CP.PRODUCTO_PRECIO_UNITARIO)
    ) / MIN(CP.PRODUCTO_PRECIO_UNITARIO) PRECIO_PROMEDIO
FROM HARAKIRI.BI_HECHO_COMPRA_PRODUCTO CP
INNER JOIN HARAKIRI.BI_TIEMPO T ON CP.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
INNER JOIN HARAKIRI.BI_PROVEEDOR P ON CP.PROVEEDOR_CUIT = P.PROVEEDOR_CUIT
GROUP BY T.TIEMPO_ANIO, P.PROVEEDOR_RAZON_SOCIAL
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM HARAKIRI.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL)
PRINT('View AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL creada. Cant filas: ' + @CANTIDAD_REGISTROS)
